{% set name = "tilt" %}
{% set version = "2.6.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 35a99bba2adf7c1e362f5b48f9b581cce4edfba98117e34696dde6d308d84770

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://github.com/jeremyevans/tilt
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: |
    Generic interface to multiple Ruby template engines
  description:
  doc_url: https://github.com/jeremyevans/tilt
  dev_url: https://github.com/jeremyevans/tilt

extra:
  recipe-maintainers:
    - jdmarques
